# Generated by Django 2.2.5 on 2019-12-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191229_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updates', '-timestamp']},
        ),
    ]
